hmrc/company-registration-eligibility-frontend

app/config/FrontendAppConfig.scala
app/controllers/EligibleController.scala
conf/application.conf
test/controllers/EligibleControllerSpec.scala

* https://github.com/hmrc/app-config-base/pull/77/files
Config change to do with this :point_up:

Amended continue url to be relative and not absolute

---

app/controllers/BeforeYouStartController.scala
app/controllers/IneligibleController.scala
app/controllers/PaymentOptionController.scala
app/forms/PaymentOptionFormProvider.scala
app/identifiers/PaymentOptionId.scala
app/utils/Navigator.scala
app/utils/UserAnswers.scala
app/views/ineligible_payment.scala.html
app/views/paymentOption.scala.html
conf/app.routes
conf/messages.en
it/helpers/AuthHelpers.scala
it/helpers/FakeConfig.scala
it/helpers/IntegrationSpecBase.scala
it/helpers/SessionHelper.scala
it/www/TooManyDirectorsISpec.scala
migrations/applied_migrations/PaymentOption.sh
project/FrontendBuild.scala
project/MicroService.scala
project/build.properties
project/plugins.sbt
test/controllers/BeforeYouStartControllerSpec.scala
test/controllers/PaymentOptionControllerSpec.scala
test/forms/PaymentOptionFormProviderSpec.scala
test/utils/NavigatorSpec.scala
test/views/PaymentOptionViewSpec.scala

**New feature**
Added a new page which asks if the user can pay by card or PayPal - this also has a new drop out page.

SCRS-11573 Added payment option eligibility question

---

project/FrontendBuild.scala

SCRS-12087 - Dependency uplift for the bounce of service for new https config
Bug fix

SCRS-12087 - Dependency uplift

---

project/FrontendBuild.scala
project/MicroService.scala
project/plugins.sbt

SCRS-12010 changes for new build env

SCRS-12010 changes for new build env

---

app/views/eligible.scala.html
conf/messages.en
project/plugins.sbt

SCRS-11862 Amended content on eligible page

SCRS-11862 Amended content on eligible page

---

app/assets/stylesheets/_header-adjust.scss

SCRS-11931 added blue banner to heading

SCRS-11931 added blue banner

---

app/views/secureRegister.scala.html
conf/messages.en

SCRS-11916 secure register content change

SCRS-11916 secure register content change

---

conf/application.conf

SCRS-12001 Assets Frontend uplift to 3.7.0

SCRS-12001 Assets Frontend uplift to 3.7.0

---

app/utils/Navigator.scala

SCRS-12816 altered route to skip over 5 directors page

SCRS-12816 altered route to skip over 5 directors page

---

app/utils/Navigator.scala
test/utils/NavigatorSpec.scala

SCRS-12881 removed routing to Parent Company and Shareholder pages
The second PR will have all the code removed and dependancy uplifts

SCRS-12881 removed routing to Parent Company and Shareholder pages

---

project/FrontendBuild.scala
project/plugins.sbt

SAR-4077 - Upgrade Dependencies
* [] I've included appropriate tests with any code I've added
* [] I've added my code using logical, atomic commits, squashing as appropriate - including the Jira issue number in the commit message

SAR-4077 - Upgrade Dependencies

---

conf/application.conf

SAR-4343 added config for handling SSL exception

---

conf/application.conf

Fixed session filter issue

---

app/config/FrontendAppConfig.scala

**Bug fix**
Removed the english/welsh toggle from the views

Removed english/welsh toggle from views

---

app/config/featureswitch/FeatureSwitch.scala
app/config/featureswitch/FeatureSwitchedController.scala
app/config/featureswitch/FeatureSwitching.scala
app/controllers/TakingOverBusinessController.scala
app/controllers/test/FeatureSwitchController.scala
app/views/test/feature_switch.scala.html
conf/testOnlyDoNotUseInAppConf.routes
test/controllers/TakingOverBusinessControllerSpec.scala
test/controllers/test/FeatureSwitchControllerSpec.scala

SAR-5394 Added feature switch to remove Takeover page from flow

---

project/plugins.sbt

Update sbt dependencies to fix Jenkins build

---

app/views/helpers/TitleHelper.scala
app/views/paymentOption.scala.html
app/views/secureRegister.scala.html
app/views/takingOverBusiness.scala.html
conf/messages.en

* [] I've run a dependency check to ensure all dependencies are up to date

SAR-5935 Add prefix Error to the page title when a form has errors

---

app/views/paymentOption.scala.html
app/views/secureRegister.scala.html
app/views/takingOverBusiness.scala.html
conf/messages.en

SAR-5973 adding space after the Error: prefix in the title

---

app/views/main_template.scala.html
conf/messages.en
test/controllers/test/FeatureSwitchControllerSpec.scala
test/views/ViewSpecBase.scala
test/views/behaviours/ViewBehaviours.scala

SAR-5981: add Service name to page title

---

app/views/components/text_with_bullets.scala.html
app/views/paymentOption.scala.html
test/views/behaviours/YesNoViewBehaviours.scala

SAR-6004: Add H1 within fieldset legend option to all radio helpers

---

app/config/FrontendAppConfig.scala
app/views/govuk_wrapper.scala.html
conf/messages.en

SAR-6198 - Update Footer Links

---

README.md
app/views/govuk_wrapper.scala.html
conf/application.conf
project/FrontendBuild.scala

SAR-6861: Added integration for tracking consent

---

app/config/FrontendAppConfig.scala
conf/application.conf

Add GA back into CSP

---

conf/messages.en

SAR-9913: Update apostrophes

---

app/connectors/DataCacheConnector.scala
app/models/DatedCacheMap.scala
app/repositories/SessionRepository.scala
it/helpers/SessionHelper.scala

Includes quick refactor to move the DatedCacheModel to the models package and remove unnecessary dual class implementation for the Mongo Repo.

[SAR-10155] Joda time to Java time

---

app/config/FrontendAppConfig.scala
conf/application.conf

https://github.com/hmrc/app-config-base/pull/7700

accessibilityStatementConfig

---

app/config/FrontendAppConfig.scala
app/views/components/phaseBanner.scala.html
app/views/layouts/layout.scala.html
conf/application.conf

AppConfig base:
https://github.com/hmrc/app-config-base/pull/7807

Integrate Feedback frontend

---

app/views/layouts/layout.scala.html
project/AppDependencies.scala
project/plugins.sbt

[DL-13095] play-frontend-hmrc upgrade

---

app/controllers/EligibleController.scala
conf/application.conf
test/controllers/EligibleControllerSpec.scala
test/views/EligibleViewSpec.scala

DL-13731 : remove the govt-gateway references

---

app/controllers/EligibleController.scala
conf/application.conf

DL-13731 : fixing the gateway reg login

---

app/filters/SessionIdFilter.scala
app/forms/mappings/Formatters.scala
app/models/Date.scala
app/views/paymentOption.scala.html
app/views/secureRegister.scala.html
build.sbt
project/AppDependencies.scala
project/build.properties
project/plugins.sbt
test/controllers/BeforeYouStartControllerSpec.scala

[DL-15996] Upgrade for Java 21

---

app/config/FrontendAppConfig.scala
app/config/featureswitch/FeatureSwitch.scala
app/config/featureswitch/FeatureSwitchItems.scala
app/controllers/test/FeatureSwitchController.scala
app/forms/FeatureSwitchForm.scala
app/models/FeatureSwitchModel.scala
app/views/beforeYouStart.scala.html
conf/application.conf
conf/messages.cy
conf/messages.en
test/controllers/test/FeatureSwitchControllerSpec.scala
test/views/BeforeYouStartViewSpec.scala

DL-16133 Update content on the 'check before you start' page

---

app/config/FrontendAppConfig.scala
app/controllers/IdentityVerificationController.scala
app/controllers/NeedVerifiedIdentityController.scala
app/forms/IdentityVerificationFormProvider.scala
app/identifiers/IdentityVerificationId.scala
app/models/IdentityVerificationAudit.scala
app/utils/Navigator.scala
app/views/beforeYouStart.scala.html
app/views/identityVerification.scala.html
app/views/needVerifiedIdentity.scala.html
conf/app.routes
conf/application.conf
conf/messages.cy
conf/messages.en
test/controllers/BeforeYouStartControllerSpec.scala
test/controllers/IdentityVerificationControllerSpec.scala
test/controllers/NeedVerifiedIdentityControllerSpec.scala
test/forms/IdentityVerificationFormProviderSpec.scala
test/utils/NavigatorSpec.scala
test/views/IdentityVerificationViewSpec.scala
test/views/NeedVerifiedIdentityViewSpec.scala
test/views/behaviours/YesNoViewBehaviours.scala

DL-16137 Create Identify Verification Page and Create need-verified-identity Page - DL-16137 - DL-16145

DL-16137 Create Identify Verification Page and Create need-verified-identity Page - DL-16137 - DL-16145

---

app/handlers/ErrorHandler.scala
conf/application.conf
project/AppDependencies.scala

DL-17025 : update the bobby vulnerabilities
